version: '3'
services:
  db:
    image: postgres:15-alpine3.18
    restart: always
    env_file:
      - .env
    volumes:
      - './db_data:/var/lib/postgresql/data'
    ports:
      - "${POSTGRES_PORT}:5432"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - './app:/app'